# Ballerina demo config file
    consumerKey = "IqNGHjTVhzh8escMzsEjYdDu8"
    consumerSecret = "7dAB6b21WN3i3zvpAyehmf1omHQ1lu9ZKrw2yc7JVQcEj22fPp"
    accessToken = "1014552306874871808-BsOOmrlzRBox5VbgeoJ9xYgUBgpNVo"
    accessTokenSecret = "mhh4QwmeSmxRlHEzhYb4zaV1jQY3hOSjJCkXRQGsyNNmM"
